//=============================================================================
// inc/config/cslib_hwconfig.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document. leave the sections
// inside the "$[...]" comment tags alone or they will be overwritten!
//=============================================================================

#ifndef __SILICON_LABS_CSLIB_HWCONFIG_H
#define __SILICON_LABS_CSLIB_HWCONFIG_H

// $[mux values]
#define MUX_VALUE_ARRAY \
  0x0A,     /* CS1.2 */ \
  0x0B,     /* CS1.3 */ \
  0x0C,     /* CS1.4 */ \
  0x02,     /* CS0.2 */ \
  0x01,     /* CS0.1 */ \
  0x09,     /* CS1.1 */ \
  0x03,     /* CS0.3 */ \
  0x06,     /* CS0.6 */ \
  0x0D,     /* CS1.5 */ \
// [mux values]$
// $[gain values]
#define GAIN_VALUE_ARRAY \
  0x07,     /* CS0.1 */ \
  0x07,     /* CS0.2 */ \
  0x07,     /* CS0.3 */ \
  0x07,     /* CS0.6 */ \
  0x07,     /* CS1.1 */ \
  0x07,     /* CS1.2 */ \
  0x07,     /* CS1.3 */ \
  0x07,     /* CS1.4 */ \
  0x07,     /* CS1.5 */ \
// [gain values]$
// $[accumulation values]
#define ACCUMULATION_VALUE_ARRAY \
  0x05,     /* CS0.1 */ \
  0x05,     /* CS0.2 */ \
  0x05,     /* CS0.3 */ \
  0x05,     /* CS0.6 */ \
  0x05,     /* CS1.1 */ \
  0x05,     /* CS1.2 */ \
  0x05,     /* CS1.3 */ \
  0x05,     /* CS1.4 */ \
  0x05,     /* CS1.5 */ \
// [accumulation values]$
// $[Active mode mask]
#define ACTIVE_MODE_MASK_P0   0x4E
#define ACTIVE_MODE_MASK_P1   0x3E
// [Active mode mask]$

// $[Sleep mode mask]
#define SLEEP_MODE_MASK_P0    0x4E
#define SLEEP_MODE_MASK_P1    0x3E
// [Sleep mode mask]$

#endif // __SILICON_LABS_CSLIB_HWCONFIG_H
